import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { extname, join, relative, resolve, sep } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const dist = join(root, 'dist');
const serverDir = join(dist, 'server');
const metadataDir = join(dist, '.openai');

const mimeTypes = {
  '.css': 'text/css; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.ico': 'image/x-icon',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.svg': 'image/svg+xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.webp': 'image/webp',
};

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    if (entry.name === 'server' || entry.name === '.openai') continue;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(path)));
    else files.push(path);
  }

  return files;
}

const assets = {};
for (const file of await walk(dist)) {
  const pathname = `/${relative(dist, file).split(sep).join('/')}`;
  assets[pathname] = {
    body: (await readFile(file)).toString('base64'),
    type: mimeTypes[extname(file).toLowerCase()] ?? 'application/octet-stream',
  };
}

const worker = `// Generated by scripts/package-worker.mjs. Do not edit.
const assets = ${JSON.stringify(assets)};

const securityHeaders = {
  'content-security-policy': "default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self' 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
  'referrer-policy': 'strict-origin-when-cross-origin',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
};

function decodeBase64(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

export default {
  async fetch(request) {
    if (request.method !== 'GET' && request.method !== 'HEAD') {
      return new Response('Method Not Allowed', {
        status: 405,
        headers: { allow: 'GET, HEAD', ...securityHeaders },
      });
    }

    let pathname;
    try {
      pathname = decodeURIComponent(new URL(request.url).pathname);
    } catch {
      return new Response('Bad Request', { status: 400, headers: securityHeaders });
    }

    const directKey = pathname === '/' ? '/index.html' : pathname;
    const directoryKey = pathname.endsWith('/')
      ? \`\${pathname}index.html\`
      : \`\${pathname}/index.html\`;
    const key = assets[directKey] ? directKey : directoryKey;
    const asset = assets[key];
    if (!asset) {
      return new Response('Not Found', { status: 404, headers: securityHeaders });
    }

    const headers = new Headers({
      'cache-control': key.endsWith('.html')
        ? 'public, max-age=0, must-revalidate'
        : 'public, max-age=31536000, immutable',
      'content-type': asset.type,
      ...securityHeaders,
    });

    return new Response(request.method === 'HEAD' ? null : decodeBase64(asset.body), {
      status: 200,
      headers,
    });
  },
};
`;

await mkdir(serverDir, { recursive: true });
await mkdir(metadataDir, { recursive: true });
await writeFile(join(serverDir, 'index.js'), worker);
await writeFile(
  join(metadataDir, 'hosting.json'),
  await readFile(join(root, '.openai', 'hosting.json')),
);
