import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:kt_wallet/src/market/transaction_card.dart';

TransactionCardData _data({
  String explorerUrl =
      'https://sepolia.etherscan.io/tx/'
      '0x1234567890abcdef1234567890abcdef1234567890abcdef',
  TransactionCardTone tone = TransactionCardTone.success,
  String status = 'Confirmed',
}) => TransactionCardData(
  title: 'On-chain transaction receipt',
  amount: '-0.001 ETH',
  direction: 'Sent',
  status: status,
  transactionTimeLabel: 'Transaction time',
  transactionTime: '2026-07-29 14:38',
  networkName: 'Sepolia',
  isTestnet: true,
  testnetLabel: 'TESTNET',
  explorerUrl: explorerUrl,
  scanLabel: 'Scan to verify in a block explorer',
  footer: 'Generated by KT Wallet · On-chain data is authoritative',
  tone: tone,
  tokenIconAsset: 'eth',
  networkIconAsset: 'eth',
  fields: const [
    TransactionCardField(label: 'Network', value: 'Sepolia'),
    TransactionCardField(
      label: 'From',
      value: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
      mono: true,
    ),
    TransactionCardField(
      label: 'Recipient',
      value: '0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed',
      mono: true,
    ),
    TransactionCardField(
      label: 'Transaction hash',
      value: '0x1234567890abcdef1234567890abcdef1234567890abcdef',
      mono: true,
    ),
  ],
);

({int width, int height}) _pngSize(List<int> bytes) {
  const signature = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
  expect(bytes.take(8).toList(), signature, reason: 'not a PNG');
  int be32(int at) =>
      (bytes[at] << 24) |
      (bytes[at + 1] << 16) |
      (bytes[at + 2] << 8) |
      bytes[at + 3];
  return (width: be32(16), height: be32(20));
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUpAll(() async {
    await (FontLoader(
      'Inter',
    )..addFont(rootBundle.load('fonts/Inter.ttf'))).load();
    await (FontLoader(
      'JetBrains Mono',
    )..addFont(rootBundle.load('fonts/JetBrainsMono.ttf'))).load();
  });

  test('renders a branded high-resolution transaction receipt', () async {
    final png = await renderTransactionCardPng(_data(), scale: 2);
    final size = _pngSize(png);

    expect(size.width, 1440);
    expect(size.height, greaterThan(1700));
    expect(png.length, greaterThan(5000));

    final previewPath = Platform.environment['KT_RECEIPT_PREVIEW'];
    if (previewPath != null && previewPath.isNotEmpty) {
      File(previewPath)
        ..createSync(recursive: true)
        ..writeAsBytesSync(png, flush: true);
    }
  });

  test('explorer URL changes the QR', () async {
    final first = await renderTransactionCardPng(_data(), scale: 1);
    final second = await renderTransactionCardPng(
      _data(explorerUrl: 'https://solscan.io/tx/another-signature'),
      scale: 1,
    );
    expect(first, isNot(equals(second)));
  });

  test('status tone and label are visible data', () async {
    final success = await renderTransactionCardPng(_data(), scale: 1);
    final failed = await renderTransactionCardPng(
      _data(tone: TransactionCardTone.failed, status: 'Failed'),
      scale: 1,
    );
    expect(success, isNot(equals(failed)));
  });

  test('refuses to create a receipt without a verification URL', () async {
    expect(
      () => renderTransactionCardPng(_data(explorerUrl: '')),
      throwsArgumentError,
    );
  });
}
